# Generated by Django 3.2.7 on 2021-09-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_phone_no_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
