# Generated by Django 3.2.7 on 2021-09-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20210921_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
