# Generated by Django 3.2.7 on 2021-09-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_phone_no_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_no',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
