# Generated by Django 3.2.7 on 2021-09-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_alter_phone_no_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_no',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
