# Generated by Django 3.2.7 on 2021-09-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_alter_phone_no_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='label',
        ),
        migrations.AddField(
            model_name='phone_no',
            name='label',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Work', 'Work'), ('Mobile', 'Mobile')], default='Home', max_length=20),
        ),
    ]
